server:
  port: 8082
  servlet:
    context-path: /api/v1
spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    drive-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    format_sql: true
    show_sql: true
    genetate-ddl: false
    database-platform: org.hibernate.dialect.PostgreSQL82Dialect